"""Highlight and export helpers for watermark tokens."""

from __future__ import annotations

import html
from typing import Sequence

from .schemes.base import TokenInfo

# Soft yellow — matches design plan
HIGHLIGHT_BG = "#FEF08A"
HIGHLIGHT_CSS = f"""
.watermark-signal {{
  background-color: {HIGHLIGHT_BG};
  border-radius: 2px;
  padding: 0 1px;
}}
.watermark-output {{
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
  white-space: pre-wrap;
  word-break: break-word;
  line-height: 1.6;
  font-size: 0.95rem;
}}
""".strip()


def tokens_to_spans(tokens: Sequence[TokenInfo]) -> list[dict]:
    """Convert TokenInfo list to simple span dicts for APIs/UI."""
    return [
        {
            "text": t.text,
            "is_signal": t.is_signal,
            "start": t.start,
            "end": t.end,
            "index": t.index,
        }
        for t in tokens
    ]


def tokens_to_html(
    tokens: Sequence[TokenInfo],
    *,
    show_highlights: bool = True,
    wrap: bool = True,
    include_style: bool = True,
) -> str:
    """
    Render tokens as HTML with soft yellow marks on signal tokens.

    Uses <mark class="watermark-signal"> for contributing tokens.
    """
    parts: list[str] = []
    for t in tokens:
        escaped = html.escape(t.text)
        if show_highlights and t.is_signal:
            title = ' title="Contributes to watermark signal"'
            parts.append(f'<mark class="watermark-signal"{title}>{escaped}</mark>')
        else:
            parts.append(escaped)

    body = "".join(parts)
    if wrap:
        body = f'<div class="watermark-output">{body}</div>'
    if include_style:
        return f"<style>{HIGHLIGHT_CSS}</style>\n{body}"
    return body


def tokens_to_annotated_document(
    tokens: Sequence[TokenInfo],
    *,
    title: str = "fak-u-watermark export",
    statistics: dict | None = None,
) -> str:
    """Full HTML document for export (annotated with highlights + optional stats)."""
    stats_block = ""
    if statistics:
        rows = "".join(
            f"<tr><td>{html.escape(str(k))}</td><td>{html.escape(str(v))}</td></tr>"
            for k, v in statistics.items()
        )
        stats_block = f"""
        <h2>Statistics</h2>
        <table border="1" cellpadding="6" cellspacing="0">
          <tbody>{rows}</tbody>
        </table>
        """

    body = tokens_to_html(tokens, show_highlights=True, wrap=True, include_style=False)
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>{html.escape(title)}</title>
  <style>
    body {{ font-family: system-ui, sans-serif; max-width: 48rem; margin: 2rem auto; padding: 0 1rem; }}
    {HIGHLIGHT_CSS}
    table {{ border-collapse: collapse; margin-bottom: 1.5rem; }}
    td {{ border: 1px solid #ccc; }}
  </style>
</head>
<body>
  <h1>{html.escape(title)}</h1>
  {stats_block}
  <h2>Highlighted text</h2>
  {body}
  <p><small>Generated by fak-u-watermark · Yellow marks indicate green-list (signal) tokens.</small></p>
</body>
</html>
"""
