"""Highlight and export helpers for watermark tokens."""

from __future__ import annotations

import html
from typing import Sequence

from .schemes.base import TokenInfo

# Soft yellow — matches design plan
HIGHLIGHT_BG = "#FEF08A"
HIGHLIGHT_CSS = f"""
.watermark-output {{
  font-family: "Iowan Old Style", "Palatino Linotype", Palatino, Georgia, "Times New Roman", serif;
  font-size: 1.05rem;
  line-height: 1.75;
  letter-spacing: 0.01em;
  color: #1c1917;
  white-space: pre-wrap;
  word-break: break-word;
  padding: 1.25rem 1.5rem;
  border: 1px solid #e7e5e4;
  border-radius: 12px;
  background: #fffefb;
  max-height: min(28rem, 60vh);
  overflow: auto;
  box-shadow: 0 1px 2px rgba(28, 25, 23, 0.04);
}}
.watermark-signal {{
  background-color: {HIGHLIGHT_BG};
  border-radius: 3px;
  padding: 0.05em 0.12em;
  box-decoration-break: clone;
  -webkit-box-decoration-break: clone;
}}
.watermark-signal:hover {{
  background-color: #fde047;
  outline: 1px solid #ca8a04;
}}
.watermark-empty {{
  color: #78716c;
  font-style: italic;
  padding: 1rem;
}}
""".strip()


def tokens_to_spans(tokens: Sequence[TokenInfo]) -> list[dict]:
    """Convert TokenInfo list to simple span dicts for APIs/UI."""
    return [
        {
            "text": t.text,
            "is_signal": t.is_signal,
            "start": t.start,
            "end": t.end,
            "index": t.index,
        }
        for t in tokens
    ]


def tokens_to_html(
    tokens: Sequence[TokenInfo],
    *,
    show_highlights: bool = True,
    wrap: bool = True,
    include_style: bool = True,
) -> str:
    """
    Render tokens as readable HTML with soft yellow marks on signal tokens.

    Uses prose-friendly serif for long-form reading comfort.
    """
    if not tokens:
        body = '<p class="watermark-empty">Paste text and click Analyze to see highlights here.</p>'
        if include_style:
            return f"<style>{HIGHLIGHT_CSS}</style>\n{body}"
        return body

    parts: list[str] = []
    for t in tokens:
        escaped = html.escape(t.text)
        if show_highlights and t.is_signal:
            title = ' title="Contributes to watermark signal (green-list token)"'
            parts.append(f'<mark class="watermark-signal"{title}>{escaped}</mark>')
        else:
            parts.append(escaped)

    body = "".join(parts)
    if wrap:
        body = f'<div class="watermark-output" role="article">{body}</div>'
    if include_style:
        return f"<style>{HIGHLIGHT_CSS}</style>\n{body}"
    return body


def tokens_to_annotated_document(
    tokens: Sequence[TokenInfo],
    *,
    title: str = "fak-u-watermark export",
    statistics: dict | None = None,
) -> str:
    """Full HTML document for export (annotated with highlights + optional stats)."""
    stats_block = ""
    if statistics:
        rows = "".join(
            f"<tr><td>{html.escape(str(k))}</td><td>{html.escape(str(v))}</td></tr>"
            for k, v in statistics.items()
        )
        stats_block = f"""
        <h2>Statistics</h2>
        <table border="1" cellpadding="6" cellspacing="0">
          <tbody>{rows}</tbody>
        </table>
        """

    body = tokens_to_html(tokens, show_highlights=True, wrap=True, include_style=False)
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>{html.escape(title)}</title>
  <style>
    body {{ font-family: system-ui, sans-serif; max-width: 42rem; margin: 2rem auto; padding: 0 1.25rem; color: #1c1917; }}
    {HIGHLIGHT_CSS}
    .watermark-output {{ max-height: none; }}
    table {{ border-collapse: collapse; margin-bottom: 1.5rem; }}
    td {{ border: 1px solid #d6d3d1; padding: 0.4rem 0.6rem; }}
  </style>
</head>
<body>
  <h1>{html.escape(title)}</h1>
  {stats_block}
  <h2>Highlighted text</h2>
  {body}
  <p><small>Generated by fak-u-watermark · Yellow marks indicate green-list (signal) tokens.</small></p>
</body>
</html>
"""
